### ISSUE TITLE
[Feature] Good Stream

### ISSUE THREAD

**Issue by mikecovlee** [libmozart/mozart#35]
`std::iostream` is **tardiness**, **bloated** and **hard to use**. We should create a better one.
## Target
+ Based on System module, implemented under raw file descriptor and provide friendly APIs to manage these descriptor
+ Widely support useful functions like redirection and system level pipe
+ Support legacy `std::iostream` through `mpp::fdstream`
+ Thread safe, can use for ITCs
+ Cooperate with object serialization #33 
+ Support asynchronous operations
+ Multi-charset and wide character support

**Comment by imkiva** [comment]
And this stream can even cooperate with our new string formatter #31
